### ISSUE TITLE
Page.goto() Unable to load page

### ISSUE THREAD

**Issue by MissHajar** [grafana/xk6-browser#120]
I'm trying to open a page with generated URL and page.goto() method. Whenever the browser open and the page begin to load, it crashes and I get the error:
``` 
panic: unable to parse remote object value: cannot extract value when remote object ID is given
running (0m02.8s), 1/1 VUs, 0 complete and 0 interrupted iterations
goroutine 90 [running]:--------------------------] 1/1 VUs  02.8s/45.0s
go.k6.io/k6/js/common.Throw(...)
        go.k6.io/k6@v0.34.2-0.20211105090803-dae70006ca77/js/common/util.go:36
github.com/grafana/xk6-browser/common.(*FrameSession).onConsoleAPICalled(0xc00207c300, 0xc0034301e0)
        github.com/grafana/xk6-browser@v0.1.0/common/frame_session.go:419 +0x54e
github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1()
        github.com/grafana/xk6-browser@v0.1.0/common/frame_session.go:208 +0x357
created by github.com/grafana/xk6-browser/common.(*FrameSession).initEvents
        github.com/grafana/xk6-browser@v0.1.0/common/frame_session.go:181 +0xe7
```

I'm running on Windows and here's my script (sample URL -> won't work)

``` js
import { sleep, check, group } from "k6";
import http from "k6/http";

import launcher from "k6/x/browser";

let PaymentPageUrl = "https://www.example.com/actor/name?1565621654&data=ksmancoajd 

export default function main() {
  browser = launcher.launch("chromium", {
    args: [],
    debug: true,
    devtools: false,
    env: {},
    executablePath: null,
    headless: false,
    ignoreDefaultArgs: [],
    proxy: {},
    slowMo: "1000ms",
    timeout: "60s",
  });

  context = browser.newContext({
    ignoreHTTPSErrors: true,
    JavaScriptEnabled: true,
  });

  page = context.newPage();
  group("Navigate to Url", () => {
    try {
      page.goto(PaymentPageUrl, {
        waitUntil: "load",
      });
      console.log("=== Goto passed");
      //page.once('load', () => console.log('Page loaded!'));
    } catch (error) {
      console.log("Goto Error ==>", error);
    }
    try {
      frame = page.mainFrame();
      console.log("=== Frame set");
    } catch (error) {
      console.log("Frame Error ==>", error);
    }
    sleep(10);
    frame.waitForSelector('iframe[id="complpay-content-iframe"]');
  });
  sleep(10);
}
```

I manage to load as a test a simple documentation page and click on a link.
But for my "complex" page, I've tried a lot of things but without success.

**Comment by imiric** [comment]
Hi, thanks for reporting this!

Unfortunately I'm not able to reproduce it with your script on current `main` (baaf58c), on Linux nor on Windows 10.

Can you reproduce it consistently with this example script, or does it only happen with your real "complex" page?

This seems like a new issue, so I'll leave it open, but it's difficult to fix if we can't reproduce it. If you can provide a small real-world script (i.e. not testing `example.com`), it would help a lot.

**Comment by MissHajar** [comment]
It happens only with this kind of page.
Here are real pages that you can use:
https://payment.limonetikqualif.com/Conforama/Order/PayPage/883855542460?LmkData=bGc9ZW4tVVM= 
https://payment.limonetikqualif.com/Conforama/Order/PayPage/893424491486?LmkData=bGc9ZW4tVVM=
https://payment.limonetikqualif.com/Conforama/Order/PayPage/949673021902?LmkData=bGc9ZW4tVVM=

Due to privacy reasons, I cannot share the request that generates this URL.

I hope this helps you reproduce.

**Comment by MissHajar** [comment]
Hi @imiric, 
Previous URLs should return aborted now. Let me know if you need new ones.
Thank you for your help

**Comment by imiric** [comment]
Thanks @MissHajar. It's not needed since we have a simpler example that reproduces the issue:

```javascript
import launcher from 'k6/x/browser';

export default function() {
  const browser = launcher.launch('chromium', {
    headless: true,
  });
  const context = browser.newContext();
  const page = context.newPage();

  page.evaluate(() => {
    console.log({one: 1});
  });

  page.close();
  browser.close();
}
```

We're hoping to release a fix for it soon.

**Comment by MissHajar** [comment]
Great!
Happy to know you can reproduce. I'll wait for the fix :)

**Comment by imiric** [comment]
@MissHajar Apologies for the late response, but this should be fixed now on `main`.

Can you test by building a custom binary with `xk6 build --output xk6-browser --with github.com/grafana/xk6-browser@main` and running the script that previously failed for you?

We'll make a new release in a few days so you'll be able to use the official binary then, but just to confirm that this solved your issue. Thanks!

**Comment by MissHajar** [comment]
Hello Ivan,

Very happy to hear from you. I'll test and let you know as soon as possible.

Hajar ZAROUAL


Le mar. 30 nov. 2021 à 16:59, Ivan Mirić ***@***.***> a
écrit :

**Comment by MissHajar** [comment]
Although it seems to be better because it doesn't crash right away, the iframe still isn't loading therefore I can't go further.
I have a new Panic message 
"panic: cannot create frame session: unable to add script to evaluate for isolated world: websocket: close 1001 (going away)"

**Comment by inancgumus** [comment]
@MissHajar We're working on a fix for that error. You can follow the issue for updates, see #125.
